version: 2
jobs:
  deploy-development:
    docker:
      - image: circleci/node:14.15.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-{{ checksum "app/package.json" }}
      - run:
          name: change env and deploy
          working_directory: ~/app
          command: |
            mv ./dotenv/.env.development ./.env
            ls
            pwd
            ./deploy.sh
            # - run:
            #     name: deploy
            #     working_direcotry: app
            #     command: |
  deploy-production:
    docker:
      - image: circleci/node:14.15.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-{{ checksum "app/package.json" }}
      - run:
          name: change env
          working_directory: app
          command: mv ./dotenv/.env.production ./.env
      - run:
          name: deploy
          working_direcotry: app
          command: ./deploy.sh
workflows:
  version: 2
  deploy:
    jobs:
      - deploy-development:
          filters:
            branches:
              only:
                - develop
      - deploy-production:
          filters:
            branches:
              only:
                - main
